#ifndef PREFERENCES_ENUMS
#define PREFERENCES_ENUMS

enum CPU_ENUM {
    CPU_AMD = 1,
    CPU_INTEL = 2,
};

enum GPU_ENUM {
    GPU_AMD = 1,
    GPU_NVIDIA = 2,
};

enum FPS_AMOUNT_ENUM {
    FPS30 = 1,
    FPS60 = 2,
    FPS120 = 3,
    FPS240 = 4,
};

enum GAMING_SETTINGS_ENUM {
    GAMING_SETTINGS_LOW = 1,
    GAMING_SETTINGS_MEDIUM_HiGH = 2,
    GAMING_SETTINGS_ULTRA = 3,
    GAMING_SETTINGS_PUBG = 4,
    GAMING_SETTINGS_CYBERSPORT_OTHERS = 5,
};

enum GAMING_PREFERENCE_ENUM{
    GAMING_PREFERENCE_AAA = 1,
    GAMING_PREFERENCE_CYBERSPORT = 2,
};

enum BUDGET_ENUM {
    BUDGET_LOW = 1,
    BUDGET_MID = 2,
    BUDGET_UPPER = 3,
    BUDGET_HIGH = 4,
};

enum WORK_TYPE_ENUM {
    VIDEO = 1,
    PROGRAMMING = 2,
    AI = 3,
};

enum PROGRAMMING_GOALS_ENUM {
    SOFTWARE = 1,
    SERVERS = 2,
    GAMES = 3,
};

enum VIDEOEDIT_DEPENDING_ENUM {
    CPU_DEPENDING = 1,
    GPU_DEPENDING = 2,
};

enum SOFTWARE_PLATFORM_ENUM {
    APPLE_PLATFORM = 1,
    DESKTOP_PLATFORM = 2,
    MOBILE_PLATFORM = 3,
};

#endif